server:
  port: 9012

#feign:
#  hystrix:
#    enabled: true
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json;charset=UTF-8
#      min-request-size: 1024
#    response:
#      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_demo_hippo_fresh?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: tcuser
    filters: stat
    maxActive: 30
    initialSize: 10
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: localhost
    port: 6379
    password: tcuser
    database: 0
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 0
    
swagger:
  enable: true
  host: 127.0.0.1:5555
#===================redis===================

