server:
  port: 9013
grpc:
  server:
    port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://127.0.0.1:9100
  cloud:
    stream:
      bindings:
        inventoryReductionOutput:
          group: product
          content-type: application/json