server:
  port: 9013
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        inventoryReductionOutput:
          group: product
          content-type: application/json