server:
  port: 5555

zuul:
  routes:
    demo-auth:
      path: /demo-auth/**
      service-id: demo-auth
      sensitive-headers: '*'
    demo-auth:
      path: /demo-member/**
      service-id: demo-member
      sensitive-headers: '*'