spring:
  application:
    name: demo-gateaway
  clound:
    config:
      enabled: false
app:
  id: demo-gateaway
apollo:
  bootstrap:
    enable: true
    namespace: application

eureka:
  client:
    service-url:
      defaultZone: http://demo:demo!2018@demo-eureka-1:8762/eureka/,http://demo:demo!2018@demo-eureka-2:8763/eureka/

