server:
  port: 9011

zuul:
  routes:
    demo-auth:
      path: /demo-auth/**
      service-id: demo-auth
      sensitive-headers: '*'
  #生成环境：去除堆栈信息,使用自定义的异常处理器
  SendErrorFilter:
    error:
      disable: true